"""Initial migration

Revision ID: a3a0a441c50f
Revises: 
Create Date: 2025-09-04 12:38:25.832809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a0a441c50f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('attendance_records', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('attendance_records', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('attendance_records', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendance_records', 'working_hours',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('attendance_records', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('attendance_records', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('attendance_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.alter_column('chatbot_menus', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('chatbot_menus_id_seq'::regclass)"))
    op.alter_column('chatbot_menus', 'menu_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('chatbot_menus', 'menu_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('chatbot_menus', 'menu_icon',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('chatbot_menus', 'company_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('chatbot_menus', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_44637_sqlite_autoindex_chatbot_menus_1'), table_name='chatbot_menus')
    op.create_index(op.f('ix_chatbot_menus_id'), 'chatbot_menus', ['id'], unique=False)
    op.alter_column('chatbot_submenus', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('chatbot_submenus', 'menu_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('chatbot_submenus', 'submenu_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('chatbot_submenus', 'submenu_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('chatbot_submenus', 'api_endpoint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('chatbot_submenus', 'company_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('chatbot_submenus', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('idx_44642_sqlite_autoindex_chatbot_submenus_1'), table_name='chatbot_submenus')
    op.create_index(op.f('ix_chatbot_submenus_id'), 'chatbot_submenus', ['id'], unique=False)
    op.create_unique_constraint(None, 'chatbot_submenus', ['submenu_key'])
    op.alter_column('customer_data', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customer_data', 'customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('customer_data', 'customer_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('customer_data', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('customer_data', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('customer_data', 'total_purchases',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('customer_data', 'visit_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('customer_data', 'last_visit',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('customer_data', 'customer_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('customer_data', 'preferred_items',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('customer_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('customer_data', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_44692_sqlite_autoindex_customer_data_1'), table_name='customer_data')
    op.create_index(op.f('ix_customer_data_id'), 'customer_data', ['id'], unique=False)
    op.create_unique_constraint(None, 'customer_data', ['customer_id'])
    op.alter_column('employees', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('employees', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('employees', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('employees', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('employees', 'position',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('employees', 'employment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('employees', 'employment_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'reporting_manager',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'office_location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'salary_grade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_44662_sqlite_autoindex_employees_1'), table_name='employees')
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_unique_constraint(None, 'employees', ['employee_id'])
    op.alter_column('expense_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('expense_records', 'expense_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('expense_records', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('expense_records', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('expense_records', 'amount',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('expense_records', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('expense_records', 'vendor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('expense_records', 'payment_method',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('expense_records', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('expense_records', 'receipt_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('expense_records', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('expense_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_44682_sqlite_autoindex_expense_records_1'), table_name='expense_records')
    op.create_index(op.f('ix_expense_records_id'), 'expense_records', ['id'], unique=False)
    op.create_unique_constraint(None, 'expense_records', ['expense_id'])
    op.alter_column('hr_support_tickets', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hr_support_tickets', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('hr_support_tickets', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('hr_support_tickets', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('hr_support_tickets', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('hr_support_tickets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               nullable=False)
    op.alter_column('hr_support_tickets', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'assigned_to',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'resolved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'resolution_notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.create_index(op.f('ix_hr_support_tickets_id'), 'hr_support_tickets', ['id'], unique=False)
    op.alter_column('inventory_items', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('inventory_items', 'item_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('inventory_items', 'item_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('inventory_items', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('inventory_items', 'current_stock',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('inventory_items', 'minimum_stock',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'unit_price',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('inventory_items', 'supplier_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('inventory_items', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('inventory_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_44687_sqlite_autoindex_inventory_items_1'), table_name='inventory_items')
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_unique_constraint(None, 'inventory_items', ['item_code'])
    op.alter_column('leave_applications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('leave_applications', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('leave_applications', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('leave_applications', 'leave_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('leave_applications', 'from_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('leave_applications', 'to_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('leave_applications', 'total_days',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('leave_applications', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('leave_applications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('leave_applications', 'approved_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('leave_applications', 'comments',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('leave_applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_leave_applications_id'), 'leave_applications', ['id'], unique=False)
    op.alter_column('marketing_campaigns', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('marketing_campaigns', 'campaign_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('marketing_campaigns', 'campaign_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('marketing_campaigns', 'target_audience',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('marketing_campaigns', 'message_content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               nullable=False)
    op.alter_column('marketing_campaigns', 'budget',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'reach_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'engagement_rate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'launched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_marketing_campaigns_id'), 'marketing_campaigns', ['id'], unique=False)
    op.alter_column('payslips', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('payslips', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('payslips', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('payslips', 'pay_period',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'pay_period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payslips', 'pay_period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payslips', 'basic_salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'allowances',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'gross_salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'deductions',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'net_salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('payslips', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('payslips', 'download_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('payslips', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.alter_column('promotions', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('promotions', 'promotion_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('promotions', 'promotion_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('promotions', 'discount_percentage',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('promotions', 'discount_amount',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('promotions', 'valid_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('promotions', 'applicable_items',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('promotions', 'minimum_purchase',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('promotions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('promotions', 'usage_count',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('promotions', 'total_savings',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('promotions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_promotions_id'), 'promotions', ['id'], unique=False)
    op.alter_column('sales_records', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sales_records', 'merchant_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('sales_records', 'product_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('sales_records', 'quantity',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('sales_records', 'revenue',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('sales_records', 'sale_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('sales_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_sales_records_id'), 'sales_records', ['id'], unique=False)
    op.alter_column('staff_messages', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('staff_messages', 'message_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('staff_messages', 'from_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('staff_messages', 'to_user',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('staff_messages', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('staff_messages', 'message_content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               nullable=False)
    op.alter_column('staff_messages', 'priority',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('staff_messages', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('staff_messages', 'message_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('staff_messages', 'sent_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('staff_messages', 'read_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_44697_sqlite_autoindex_staff_messages_1'), table_name='staff_messages')
    op.create_index(op.f('ix_staff_messages_id'), 'staff_messages', ['id'], unique=False)
    op.create_unique_constraint(None, 'staff_messages', ['message_id'])
    op.alter_column('work_schedules', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('work_schedules', 'employee_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('work_schedules', 'employee_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('work_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('work_schedules', 'shift_start',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('work_schedules', 'shift_end',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('work_schedules', 'break_duration',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('work_schedules', 'total_hours',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('work_schedules', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('work_schedules', 'assigned_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('work_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('work_schedules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.alter_column('work_schedules', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('work_schedules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('work_schedules', 'assigned_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('work_schedules', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('work_schedules', 'total_hours',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('work_schedules', 'break_duration',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('work_schedules', 'shift_end',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('work_schedules', 'shift_start',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('work_schedules', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('work_schedules', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('work_schedules', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('work_schedules', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'staff_messages', type_='unique')
    op.drop_index(op.f('ix_staff_messages_id'), table_name='staff_messages')
    op.create_index(op.f('idx_44697_sqlite_autoindex_staff_messages_1'), 'staff_messages', ['message_id'], unique=True)
    op.alter_column('staff_messages', 'read_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('staff_messages', 'sent_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('staff_messages', 'message_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('staff_messages', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('staff_messages', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('staff_messages', 'message_content',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('staff_messages', 'subject',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('staff_messages', 'to_user',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('staff_messages', 'from_user',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('staff_messages', 'message_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('staff_messages', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_sales_records_id'), table_name='sales_records')
    op.alter_column('sales_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('sales_records', 'sale_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sales_records', 'revenue',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('sales_records', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('sales_records', 'product_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('sales_records', 'merchant_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('sales_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_promotions_id'), table_name='promotions')
    op.alter_column('promotions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('promotions', 'total_savings',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'usage_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('promotions', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'minimum_purchase',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'applicable_items',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'valid_until',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('promotions', 'valid_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('promotions', 'discount_amount',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('promotions', 'discount_percentage',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('promotions', 'promotion_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('promotions', 'promotion_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('promotions', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.alter_column('payslips', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('payslips', 'download_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payslips', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payslips', 'net_salary',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'deductions',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'gross_salary',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'allowances',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'basic_salary',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'pay_period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payslips', 'pay_period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payslips', 'pay_period',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('payslips', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_marketing_campaigns_id'), table_name='marketing_campaigns')
    op.alter_column('marketing_campaigns', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'launched_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'engagement_rate',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'reach_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'budget',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('marketing_campaigns', 'message_content',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_campaigns', 'target_audience',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_campaigns', 'campaign_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_campaigns', 'campaign_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_campaigns', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_leave_applications_id'), table_name='leave_applications')
    op.alter_column('leave_applications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('leave_applications', 'comments',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('leave_applications', 'approved_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('leave_applications', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('leave_applications', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_applications', 'total_days',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('leave_applications', 'to_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('leave_applications', 'from_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('leave_applications', 'leave_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_applications', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_applications', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('leave_applications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'inventory_items', type_='unique')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.create_index(op.f('idx_44687_sqlite_autoindex_inventory_items_1'), 'inventory_items', ['item_code'], unique=True)
    op.alter_column('inventory_items', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('inventory_items', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('inventory_items', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'supplier_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'unit_price',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_items', 'minimum_stock',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('inventory_items', 'current_stock',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
    op.alter_column('inventory_items', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_items', 'item_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_items', 'item_code',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_items', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_hr_support_tickets_id'), table_name='hr_support_tickets')
    op.alter_column('hr_support_tickets', 'resolution_notes',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'resolved_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'assigned_to',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'priority',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('hr_support_tickets', 'description',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hr_support_tickets', 'subject',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hr_support_tickets', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hr_support_tickets', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hr_support_tickets', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('hr_support_tickets', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'expense_records', type_='unique')
    op.drop_index(op.f('ix_expense_records_id'), table_name='expense_records')
    op.create_index(op.f('idx_44682_sqlite_autoindex_expense_records_1'), 'expense_records', ['expense_id'], unique=True)
    op.alter_column('expense_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('expense_records', 'approved_by',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expense_records', 'receipt_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expense_records', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expense_records', 'payment_method',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_records', 'vendor_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expense_records', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('expense_records', 'amount',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_records', 'description',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_records', 'category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_records', 'expense_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('expense_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.create_index(op.f('idx_44662_sqlite_autoindex_employees_1'), 'employees', ['employee_id'], unique=True)
    op.alter_column('employees', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('employees', 'salary_grade',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'office_location',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'reporting_manager',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'employment_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'employment_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'position',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'department',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('employees', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'customer_data', type_='unique')
    op.drop_index(op.f('ix_customer_data_id'), table_name='customer_data')
    op.create_index(op.f('idx_44692_sqlite_autoindex_customer_data_1'), 'customer_data', ['customer_id'], unique=True)
    op.alter_column('customer_data', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('customer_data', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('customer_data', 'preferred_items',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'customer_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'last_visit',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('customer_data', 'visit_count',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'total_purchases',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('customer_data', 'customer_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('customer_data', 'customer_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('customer_data', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'chatbot_submenus', type_='unique')
    op.drop_index(op.f('ix_chatbot_submenus_id'), table_name='chatbot_submenus')
    op.create_index(op.f('idx_44642_sqlite_autoindex_chatbot_submenus_1'), 'chatbot_submenus', ['submenu_key'], unique=True)
    op.alter_column('chatbot_submenus', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chatbot_submenus', 'company_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chatbot_submenus', 'api_endpoint',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chatbot_submenus', 'submenu_title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chatbot_submenus', 'submenu_key',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chatbot_submenus', 'menu_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('chatbot_submenus', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_chatbot_menus_id'), table_name='chatbot_menus')
    op.create_index(op.f('idx_44637_sqlite_autoindex_chatbot_menus_1'), 'chatbot_menus', ['menu_key'], unique=True)
    op.alter_column('chatbot_menus', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chatbot_menus', 'company_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chatbot_menus', 'menu_icon',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('chatbot_menus', 'menu_title',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chatbot_menus', 'menu_key',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('chatbot_menus', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('chatbot_menus_id_seq'::regclass)"))
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.alter_column('attendance_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('attendance_records', 'location',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance_records', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('attendance_records', 'working_hours',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('attendance_records', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendance_records', 'employee_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('attendance_records', 'employee_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('attendance_records', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
